#!/bin/sh

name="checkpath"

. /alcove-hooks/00-common.in

start() {
	checkpath -d /tmp/checkpath \
		/tmp/checkpath/subdir

	checkpath -d -o nobody:root /tmp/checkpath/subdir

	checkpath -f -o root:www-data /tmp/checkpath/file1

	checkpath -p -m 640 /tmp/checkpath/mypipe.fifo
}

stop() {
	rm -r /tmp/checkpath
}

status() {
	shouldbe "root:root" stat -c '%U:%G' "/tmp/checkpath"
	shouldbe "nobody:root" stat -c '%U:%G' "/tmp/checkpath/subdir"
	shouldbe "root:root" stat -c '%U:%G' "/tmp/checkpath"
	shouldbe "root:www-data" stat -c '%U:%G' "/tmp/checkpath/file1"
	shouldbe "0775" stat -c '%04a' "/tmp/checkpath/subdir"
	shouldbe "0640" stat -c '%04a' "/tmp/checkpath/mypipe.fifo"

	checkpath -f "/tmp/checkpath/subdir/file2"
	shouldbe 'root:root' stat -c '%U:%G' "/tmp/checkpath/subdir/file2"
	shouldbe '0664' stat -c '%04a' "/tmp/checkpath/subdir/file2"

	checkpath -F '/tmp/checkpath/subdir/file2'
	shouldbe '0' stat -c '%s' "/tmp/checkpath/subdir/file2"

	checkpath -D '/tmp/checkpath/subdir'
	shouldbe 'root:root' stat -c '%U:%G' "/tmp/checkpath/subdir"
	shouldbe '' stat -c '%s' "/tmp/checkpath/subdir/file2"
	
	# it's a error test
	#shouldbe '19' stat -c '%s' "/tmp/checkpath/subdir/file2"
}

action "${1}"

