#!/bin/sh

name="aria2"
command="/usr/bin/aria2c"
pidfile="/var/run/aria2.pid"
: "${command_user:="aria2"}"
: "${cfgfile:="/etc/aria2.conf"}"
command_args="--enable-rpc=true --conf-path=${cfgfile}"
command_background="yes"
#output_log="/var/lib/arai2/aria2.log"
#error_log="/var/lib/aria2/aria2.err"


. /alcove-hooks/00-common.in


start_pre() {
	checkpath -f -m 640 -o aria2 \
		/var/lib/aria2/aria2.log \
		/var/lib/aria2/aria2.err \
		/var/lib/aria2/aria2.session
}


action "${1}"

