#!/bin/sh

name="qbittorrent-nox"
command="/usr/bin/qbittorrent-nox"
command_args_background="-d"
command_background="yes"
command_user="qbittorrent:qbittorrent"
pidfile="/var/run/${name}.pid"

. /alcove-hooks/00-common.in

action "${1}"
